pull_request_rules:
  # backports from main branch
  - name: backport main patches to 21.04 branch
    conditions:
      - base=main
      - label=backport-to-21.04
    actions:
      backport:
        branches:
          - stable

  - name: backport main patches to 20.08 branch
    conditions:
      - base=main
      - label=backport-to-20.08
    actions:
      backport:
        branches:
          - old-stable

  - name: port main patches to middleware branch
    conditions:
      - base=main
      - label=backport-to-middleware
    actions:
      backport:
        branches:
          - middleware

  # backports from 21.04 release branch
  - name: port 21.04 patches to main branch
    conditions:
      - base=stable
      - label=backport-to-main
    actions:
      backport:
        branches:
          - main

  - name: backport 21.04 patches to 20.08 branch
    conditions:
      - base=stable
      - label=backport-to-20.08
    actions:
      backport:
        branches:
          - old-stable

  - name: port 21.04 patches to middleware branch
    conditions:
      - base=stable
      - label=backport-to-middleware
    actions:
      backport:
        branches:
          - middleware

  # ports from 20.08 release branch
  - name: port 20.08 patches to main branch
    conditions:
      - base=old-stable
      - label=backport-to-main
    actions:
      backport:
        branches:
          - main

  - name: port 20.08 patches to 21.04 branch
    conditions:
      - base=old-stable
      - label=backport-to-21.04
    actions:
      backport:
        branches:
          - stable

  - name: port 20.08 patches to middleware branch
    conditions:
      - base=old-stable
      - label=backport-to-middleware
    actions:
      backport:
        branches:
          - middleware
