name: Container Image Builds

on:
  push:
    branches: [ main ]
    tags: ["v*"]

jobs:
  images:
    name: Build and upload container images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Find reference version
        uses: greenbone/actions/reference-version@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
          file: .docker/main.Dockerfile

  trigger-openvas:
    needs: images
    name: "Trigger docker "
    runs-on: ubuntu-latest
    steps:
      - name: Trigger openvas container image build
        run: |
          curl -X POST https://api.github.com/repos/greenbone/openvas-scanner/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u greenbonebot:${{ secrets.GREENBONE_BOT_TOKEN }} \
          --data '{"event_type": "update-images"}'

