name: Build and upload docker images

on:
  push:
    branches: [ main, oldstable, stable ]

jobs:
  upload-testing:
    name: "Upload testing docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        uses: greenbone/actions/reference-version@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "Build and push ${{ github.repository }}:${{matrix.compiler}}-testing-${{ env.VERSION }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{matrix.compiler}}-testing-${{ env.VERSION }}
          file: .docker/testing/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}

  upload-build:
    needs: upload-testing
    name: "Upload build docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        uses: greenbone/actions/reference-version@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "Build and push ${{ github.repository }}:${{matrix.compiler}}-build-${{ env.VERSION }}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{matrix.compiler}}-build-${{ env.VERSION }}
          file: .docker/build/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}
